mysql:
  url: 127.0.0.1
  port: 3306

redis:
  url: 127.0.0.1
  port: 6379
  password: A123456

nacos:
  url: 127.0.0.1
  port: 8848

rabbitmq:
  url: 127.0.0.1
  port: 5672
  username: flashpipi
  password: A123456