host-url: 192.168.247.149

spring:
  application:
    name: community-file-service
  datasource:
    username: root
    password: A123456
    url: jdbc:mysql://${host-url}:3306/db_community_file?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${host-url}
      database: 0
      password: A123456
  cloud:
    nacos:
      discovery:
        server-addr: ${host-url}:8848
  rabbitmq:
    host: ${host-url}
    port: 5672
    username: flashpipi
    password: A123456
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: tb_

server:
  port: 11004
  servlet:
    context-path: /file

file:
  default-save-path: F:\fileUpload\
  chunk-size: 5242880  # 5MB
