spring:
  profiles:
    active: devLocal
  application:
    name: community-file-service
  datasource:
    username: root
    password: A123456
    url: jdbc:mysql://${mysql.url}:${mysql.port}/db_community_file?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${redis.url}
      port: ${redis.port}
      database: 0
      password: ${redis.password}
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:${nacos.port}
  rabbitmq:
    host: ${rabbitmq.url}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: tb_

server:
  port: 11004
  servlet:
    context-path: /file

file:
  #  default-save-path: F:\fileUpload\      # Windows环境下默认存储路径
  default-save-path: /home/guox/file/      # Linux环境下默认存储路径
  default-output-path: /home/guox/file/output/      # Linux环境下默认存储路径
  default-ffmpeg-path: /usr/bin/ffmpeg
  chunk-size: 5242880  # 5MB 分块大小默认为5MB

xxl:
  job:
    admin:
      accessToken: default_token
      timeout: 3
      addresses: http://192.168.2.4:18080/xxl-job-admin
    executor:
      appname: file-clean-executor
      address:
      ip:
      port: 9999
      logpath: /home/guox/tmp_logs/xxl_job
      logretentiondays: 30