host-url: 192.168.247.149

spring:
  application:
    name: community-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: ${host-url}:8848
    gateway:
      mvc:
        routes:
          - id: community-auth-service
            uri: lb://community-auth-service
            predicates:
              - Path=${request_prefix}/auth/**
            filters:
              - StripPrefix=2
          - id: community-user-service
            uri: lb://community-user-service
            predicates:
              - Path=${request_prefix}/user/**
            filters:
              - StripPrefix=2
          - id: community-uploader-service
            uri: lb://community-file-service
            predicates:
              - Path=${request_prefix}/file/**
            filters:
              - StripPrefix=2

server:
  port: 11000

request_prefix: /api/iic