host-url: 192.168.247.149

spring:
  application:
    name: community-video-service
  datasource:
    username: root
    password: A123456
    url: jdbc:mysql://${host-url}:3306/db_community_video?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${host-url}
      database: 0
      password: A945855456
  cloud:
    nacos:
      discovery:
        server-addr: ${host-url}:8848
  rabbitmq:
    host: ${host-url}
    port: 5672
    username: flashpipi
    password: A123456
    virtual-host: /

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: tb_

server:
  port: 11003
  servlet:
    context-path: /video